### ISSUE TITLE
Impossible to play any song with Lavalink

### ISSUE THREAD

**Issue by Faholan** [napstr/Magma#32]
Now, each time I try to play a song with Lavalink, I get this error :
`Connection closed due to [4006 SESSION_NO_LONGER_VALID] Session is no longer valid.. This could indicate an issue with the magma library or your usage of it. Please get in touch. https://github.com/napstr/Magma/issues`

So, here I am... I already tried updating Lavalink to the latest release, and the strange thing is that it was pefectly working not a long time ago.

How do I fix that ?

**Comment by schnapster** [comment]
Lavalink has not been to merging the latest Magma patches, so I'm afraid you need talk to the maintainers of that repo, as there is nothing Magma can do here.

**Comment by freyacodes** [comment]
Consider using the dev branch, which doesn't use Magma
